version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DB_NAME}"
      PG_DATA: /var/lib/postgresql/data
    networks:
      - transcendence-network
    volumes:
    - ./pgdata:/var/lib/postgresql/data

  back-end:
    container_name: "back-end_${NODE_ENV}"
    image: "back-end_${NODE_ENV}"
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: ./back-end
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    entrypoint: ["./wait-for-postgres.sh", "npm", "run", "start:${NODE_ENV}"]
    env_file:
      - .env
    ports:
      - ${NESTJS_PORT}:${NESTJS_PORT}
      - 5555:5555
    networks:
      - transcendence-network
    depends_on:
      - postgres
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  transcendence-network:

